project:
  type: book
  output-dir: docs

book:
  title: "rw-book"
  author: "Michael Sumner"
  date: "2024-03-03"
  chapters:
    - index.qmd
    - intro.qmd
    - r-image.qmd
    - ghrsst-netcdf.qmd
    - grids.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt



