## Exactextract and fasterize, polygon rasterization and polygon extraction are complements

when exactextract runs on a polygon layer to extract values and summarize them per polygon (you get exact weighting where the polygon only partially overlaps an area pixel), it does this by generating a polygon overlay literally of the polygon and the pixel-as-polygon with GEOS, it does this fast by detecting which cells are hit by the polygon boundary and then flood fills to determine the rest (all weight 1, fully within the polygon). Then it aggregates the values by those weights and spits out the answer. If you store the weights and the cells (boundary ones, the fill ones can be run-length encoded by rows), you actually have a very compact representation of that polygon layer, rasterized.  Extraction and rasterization are closely related, and to regridding as well. 

With only approximate methods (centre of cell is in the polygon), it’s even faster (as proved by {fasterize} on CRAN) and it can be represented abstractly (as proved by my hypertidy/controlledburn on gh). I would like to combine what exactextract does with what fasterize does, allow approximate method for speed, exact method when needed and consolidate polygon-extraction with its intermediate step which is polygon-rasterization. 

The same could certainly be done with lines, and I think this has some exciting possibilities for overlaying disparate grids like pointed to in the "conservative aggregation" post. I don’t see anyone working on this consolidation, I can just get by in the C++ required (I maintain fasterize now, and I’ve bent exactextract to give me the index output rather than the calculations), and I have talked to Dan Baston about this – it’s too abstract for the main users of exactextract though. I think there’s real potential here to take lessons from R into Python and get a pretty profound super-technique working. 
